CREATE TABLE IF NOT EXISTS backing_tracks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  song_id INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  volume REAL NOT NULL DEFAULT 1.0,
  repeat INTEGER NOT NULL DEFAULT 0,
  start_paused INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
